### ISSUE TITLE
Missing names in tracerinfo.dat cause type mismatch error upon read

### ISSUE THREAD

**Issue by lizziel** [darothen/xbpch#12]
Hi Daniel,

In order to successfully read GEOS-Chem 12.0.3 binary benchmark output I had to manually insert short and long names into tracerinfo.dat for ND21 tracers # 3 and # 60. Otherwise I got a type mismatch error since the 2nd entry for those tracers in the absence of the name columns was float (concentration) rather than string. 

These names were blank in tracerinfo.dat due to a bug in GEOS-Chem which I just pushed a fix for in dev/12.1.0. However, anyone trying to use xbpch with ND21 output from recent older versions will run into this problem. For backwards compatibility I recommend adding some handling to check if the 2nd entry is float upon read of tracerinfo.dat. If the type is float then the names are missing in the file and dummy names should be assigned, allowing the read to proceed.

Lizzie (GEOS-Chem Support Team)

**Comment by darothen** [comment]
It turns out that this edge case isn't very easy to deal with programmatically because we'd have to make many assumptions about the resulting format of `tracerinfo.dat`. If the short/long names are recorded as whitespace then the current logic works fine. If they're just missing columns (e.g. the tracer concentration was the first value) things get parsed as strings and it's tricky to explicitly figure out which column is missing.

Since this only impacts one version of GEOS-Chem and doesn't necessarily result in a bad output file, I've patched in an explicit `UserWarning` which directs the user to manually inspect tracerinfo.dat if this edge case is caught.
