### ISSUE TITLE
Depreciating PyGChem and redirecting users to xbpch

### ISSUE THREAD

**Issue by benbovy** [darothen/xbpch#6]
@darothen do you think that I can safely add a redirection note to xbpch in PyGChem's readme file?

The goal of PyGChem was to provide the minimal set of features needed to connect GEOS-Chem to the Python Scientific Stack. However,

- PyGChem is not being maintained anymore, while xbpch is.
- PyGChem provides the necessary tools to read the bpch format into iris cubes, while xbpch works with xarray. I think both are useful, but given that xarray will eventually implement conversion of `xarray.DataArray` objects to `iris.cube.Cube` objects, we probably don't need both features.
- for GEOS-Chem's netcdf outputs, xarray can be used directly...
- Besides reading files, the goal with PyGChem was also to provide a Python interface to HEMCO. But that feature has never been fully working and it perhaps makes more sense if such feature is maintained by the GC support-team.

**Comment by darothen** [comment]
@benbovy I think so... are there any iris users in the GEOS-Chem community? It might be worth checking with Tomás Sherwen and collaborators to see how they're using PyGChem though, and if there's sufficient demand, we may want to expedite completing the xarray->iris bridge. 

I do want to note that xbpch is essentially feature-complete and so development will be sporadic. The only critical feature that it doesn't have is writing from xarray->bpch, but it doesn't seem as if this is really heavily requested at this point. But the GCST is really prioritizing NetCDF output in GCC so that's not really going to be an issue in a few months.

**Comment by benbovy** [comment]
> It might be worth checking with Tomás Sherwen and collaborators to see how they're using PyGChem though.

Good point. cc @tsherwen

To be clear, I don't plan to remove the PyGChem repository anytime soon, I'm just worrying that new users should use tools that are more actively maintained and that have a better defined scope (like xbpch is/has IMO).

**Comment by darothen** [comment]
Gotcha!

In terms of new users, the GEOS-Chem Support Team is pushing for a new set of Python-based tools (GCPy) to replace GAMAP. We had a meeting earlier this summer about what that would look like, and I think I was mostly successful in convincing the group that for most applications, users can lean directly on the scientific Python stack. So what's needed is really just (a) some thin wrappers to emulate old GAMAP functionality with this stack, and (b) extensive documentation. I [built a sketch](http://danielrothenberg.com/gcpy/) of what some of the latter might look like. 

GCPy is aiming for release alongside v11-02/GCHP later this year.
